package uz.imaan.jobplatform.employer.state;

public enum EmployerState {
        MAIN_MENU,
        WAITING_FOR_REG_FULL_NAME,
        WAITING_FOR_REG_AGE,
        WAITING_FOR_REG_PASSPORT,
        WAITING_FOR_REG_PHONE,
        SETTINGS_MENU,
        WAITING_FOR_LANGUAGE,
        WAITING_FOR_TITLE,
        WAITING_FOR_CATEGORY,
        WAITING_FOR_CUSTOM_CATEGORY,
        WAITING_FOR_JOB_TYPE,
        WAITING_FOR_WORK_HOURS,
        WAITING_FOR_WORKER_COUNT,
        WAITING_FOR_SALARY,
        WAITING_FOR_REQUIREMENTS,
        WAITING_FOR_PHONE,
        NONE
}