package uz.imaan.jobplatform.telegram.JobSeekerHandler;

public enum JobSeekerState {
    NONE,
    WAITING_FOR_NAME,
    WAITING_FOR_PASSPORT,
    WAITING_FOR_PHONE,
    WAITING_FOR_JOB_TYPE,
    WAITING_FOR_CATEGORY,
    WAITING_FOR_CUSTOM_CATEGORY,
    WAITING_FOR_EXPERIENCE,
    WAITING_FOR_PROFESSION,
    WAITING_FOR_LANGUAGE,
    MAIN_MENU,
    JOB_SEARCH,
    VIEW_JOB_DETAILS,
    ACTIVE_JOBS,
    PROFILE_MENU,
    APPLICATIONS,
    WALLET_MENU,
    SETTINGS_MENU,
    APPLY_COMMENT,
    WAITING_FOR_EDIT_NAME,
    WAITING_FOR_CARD_NUMBER,
    WAITING_FOR_CARD_HOLDER,
    WAITING_FOR_PORTFOLIO
}
